CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  plate_number VARCHAR(64) NOT NULL UNIQUE,
  department VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS access_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  plate_number VARCHAR(64) NOT NULL,
  access_time TIMESTAMP NOT NULL,
  status VARCHAR(32) NOT NULL
);
